---
apiVersion: v1
kind: Pod
metadata:
  name: dummy-name
spec:
  containers:
    - args: []
      command: []
      env:
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: /opt/airflow/dags
        # - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
        #   value: postgres+psycopg2://dstandish@host.docker.internal:5432/testing
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: mysql+mysqldb://root@host.docker.internal:3306/testing
      envFrom: []
      image: this-is-no-used-doesnt-matter
      imagePullPolicy: Never
      name: base
      ports: []
      volumeMounts:
        - mountPath: /opt/airflow/logs
          name: any-name-logs
        - mountPath: /opt/airflow/dags
          name: any-name-dags
          readOnly: true      
  hostNetwork: false
  restartPolicy: Never
  securityContext:
    runAsUser: 50000
    fsGroup: 50000
  volumes:
    - name: any-name-dags
      persistentVolumeClaim:
        claimName: local-dags-pvc
    - name: any-name-logs
      persistentVolumeClaim:
        claimName: local-logs-pvc
